site_name: Dataget
repo_name: cgarciae/dataget
repo_url: https://github.com/cgarciae/dataget

theme:
  name: material

nav:
  - Introduction: index.md
  - Advanced Usage: advanced-usage.md
  - Available Datasets:
      - kaggle: datasets/kaggle.md
      - toy:
          - spirals: datasets/toy/spirals.md
      - vision:
          - mnist: datasets/vision/mnist.md
  - Creating a Dataset: dataset.md

extra:
  search:
    language: en
  social:
    - type: github
      link: https://github.com/cgarciae
    - type: twitter
      link: https://twitter.com/cgarciae88
    - type: linkedin
      link: https://www.linkedin.com/in/cgarciae

markdown_extensions:
  - admonition
  - codehilite

plugins:
  - search
  - mkdocstrings
